name: Next.js CI
on:
  - pull_request
jobs:
  nextjs:
    environment: Production
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: npm ci

      - name: Build
        env:
          NEXT_PUBLIC_RESAS_API_URI: ${{ secrets.NEXT_PUBLIC_RESAS_API_URI }}
          NEXT_PUBLIC_RESAS_API_KEY: ${{ secrets.NEXT_PUBLIC_RESAS_API_KEY }}
        run: npm run build

      - name: Test
        run: npm run test:ci
